// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdminSidebar: typeof import('./src/components/AdminSidebar.vue')['default']
    Enter: typeof import('./src/components/Enter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PopMessage: typeof import('./src/components/PopMessage.vue')['default']
    SingleArticle: typeof import('./src/components/SingleArticle.vue')['default']
    SingleCategories: typeof import('./src/components/SingleCategories.vue')['default']
    SingleObservatories: typeof import('./src/components/SingleObservatories.vue')['default']
    SingleOrganization: typeof import('./src/components/SingleOrganization.vue')['default']
    SingleStargazer: typeof import('./src/components/SingleStargazer.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
    TitleBox: typeof import('./src/components/TitleBox.vue')['default']
  }
}

export { }
